"""initial schema

Revision ID: 3e4307317740
Revises: 
Create Date: 2026-09-19 14:40:01.453952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e4307317740'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('api_key_prefix', sa.String(), nullable=True),
    sa.Column('api_key_hash', sa.String(), nullable=True),
    sa.Column('daraja_environment', sa.String(), nullable=True),
    sa.Column('daraja_shortcode', sa.String(), nullable=True),
    sa.Column('daraja_consumer_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('daraja_consumer_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('daraja_passkey_enc', sa.LargeBinary(), nullable=True),
    sa.Column('daraja_callback_base_url', sa.String(), nullable=True),
    sa.Column('b2c_shortcode', sa.String(), nullable=True),
    sa.Column('b2c_initiator_name', sa.String(), nullable=True),
    sa.Column('b2c_security_credential_enc', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_merchants_api_key_prefix'), 'merchants', ['api_key_prefix'], unique=True)
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_index(op.f('ix_merchants_status'), 'merchants', ['status'], unique=False)
    op.create_table('api_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_logs_merchant_created', 'api_request_logs', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_created_at'), 'api_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_id'), 'api_request_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_merchant_id'), 'api_request_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_request_id'), 'api_request_logs', ['request_id'], unique=False)
    op.create_table('disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('originator_conversation_id', sa.String(), nullable=True),
    sa.Column('mpesa_receipt', sa.String(), nullable=True),
    sa.Column('result_desc', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursements_conversation_id'), 'disbursements', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_disbursements_created_at'), 'disbursements', ['created_at'], unique=False)
    op.create_index(op.f('ix_disbursements_id'), 'disbursements', ['id'], unique=False)
    op.create_index(op.f('ix_disbursements_idempotency_key'), 'disbursements', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_disbursements_merchant_id'), 'disbursements', ['merchant_id'], unique=False)
    op.create_index('ix_disbursements_merchant_status', 'disbursements', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_disbursements_mpesa_receipt'), 'disbursements', ['mpesa_receipt'], unique=False)
    op.create_index(op.f('ix_disbursements_status'), 'disbursements', ['status'], unique=False)
    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_id'), 'payment_links', ['id'], unique=False)
    op.create_index(op.f('ix_payment_links_merchant_id'), 'payment_links', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_links_slug'), 'payment_links', ['slug'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('mpesa_receipt', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_checkout_request_id'), 'payments', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=False)
    op.create_index('ix_payments_merchant_created', 'payments', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index('ix_payments_merchant_status', 'payments', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_mpesa_receipt'), 'payments', ['mpesa_receipt'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_mpesa_receipt'), table_name='payments')
    op.drop_index('ix_payments_merchant_status', table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_index('ix_payments_merchant_created', table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_checkout_request_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_links_slug'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_merchant_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_id'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_index(op.f('ix_disbursements_status'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_mpesa_receipt'), table_name='disbursements')
    op.drop_index('ix_disbursements_merchant_status', table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_merchant_id'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_idempotency_key'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_id'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_created_at'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_conversation_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_index(op.f('ix_api_request_logs_request_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_merchant_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_created_at'), table_name='api_request_logs')
    op.drop_index('ix_api_logs_merchant_created', table_name='api_request_logs')
    op.drop_table('api_request_logs')
    op.drop_index(op.f('ix_merchants_status'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_api_key_prefix'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
